# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/framespace/framespace.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/framespace/framespace.proto',
  package='framespace',
  syntax='proto3',
  serialized_pb=_b('\n!proto/framespace/framespace.proto\x12\nframespace\")\n\x04\x41xis\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"(\n\x03Key\x12\r\n\x05value\x18\x01 \x01(\t\x12\x12\n\nkeySpaceId\x18\x02 \x01(\x05\"\xca\x01\n\x08KeySpace\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1e\n\x04\x61xis\x18\x03 \x01(\x0b\x32\x10.framespace.Axis\x12\x1d\n\x04keys\x18\x04 \x03(\x0b\x32\x0f.framespace.Key\x12\x34\n\x08metadata\x18\x05 \x03(\x0b\x32\".framespace.KeySpace.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\">\n\tDimension\x12\x12\n\nkeySpaceId\x18\x01 \x01(\x05\x12\x1d\n\x04keys\x18\x02 \x03(\x0b\x32\x0f.framespace.Key\"{\n\x04\x43\x65ll\x12\x14\n\nfloat_data\x18\x01 \x01(\x02H\x00\x12\x12\n\x08str_data\x18\x02 \x01(\tH\x00\x12\x13\n\tbool_data\x18\x03 \x01(\x08H\x00\x12\x12\n\x08int_data\x18\x04 \x01(\x05H\x00\x12\x13\n\tsint_data\x18\x05 \x01(\x11H\x00\x42\x0b\n\tcell_type\"\xa7\x01\n\x06Vector\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\t\x12(\n\x08\x63ontents\x18\x03 \x01(\x0b\x32\x16.framespace.KeyCellMap\x12*\n\x04info\x18\x04 \x03(\x0b\x32\x1c.framespace.Vector.InfoEntry\x1a+\n\tInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xf1\x01\n\tDataFrame\x12\n\n\x02id\x18\x01 \x01(\t\x12$\n\x05major\x18\x02 \x01(\x0b\x32\x15.framespace.Dimension\x12$\n\x05minor\x18\x03 \x01(\x0b\x32\x15.framespace.Dimension\x12\x35\n\x08metadata\x18\x04 \x03(\x0b\x32#.framespace.DataFrame.MetadataEntry\x12$\n\x08\x63ontents\x18\x05 \x03(\x0b\x32\x12.framespace.Vector\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"K\n\nKeyCellMap\x12\x1c\n\x03key\x18\x01 \x01(\x0b\x32\x0f.framespace.Key\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.framespace.Cellb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_AXIS = _descriptor.Descriptor(
  name='Axis',
  full_name='framespace.Axis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='framespace.Axis.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='framespace.Axis.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=90,
)


_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='framespace.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='framespace.Key.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keySpaceId', full_name='framespace.Key.keySpaceId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=132,
)


_KEYSPACE_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='framespace.KeySpace.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='framespace.KeySpace.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='framespace.KeySpace.MetadataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=337,
)

_KEYSPACE = _descriptor.Descriptor(
  name='KeySpace',
  full_name='framespace.KeySpace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='framespace.KeySpace.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='framespace.KeySpace.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='axis', full_name='framespace.KeySpace.axis', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keys', full_name='framespace.KeySpace.keys', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='framespace.KeySpace.metadata', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_KEYSPACE_METADATAENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=337,
)


_DIMENSION = _descriptor.Descriptor(
  name='Dimension',
  full_name='framespace.Dimension',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keySpaceId', full_name='framespace.Dimension.keySpaceId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keys', full_name='framespace.Dimension.keys', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=401,
)


_CELL = _descriptor.Descriptor(
  name='Cell',
  full_name='framespace.Cell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='float_data', full_name='framespace.Cell.float_data', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='str_data', full_name='framespace.Cell.str_data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool_data', full_name='framespace.Cell.bool_data', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int_data', full_name='framespace.Cell.int_data', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sint_data', full_name='framespace.Cell.sint_data', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='cell_type', full_name='framespace.Cell.cell_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=403,
  serialized_end=526,
)


_VECTOR_INFOENTRY = _descriptor.Descriptor(
  name='InfoEntry',
  full_name='framespace.Vector.InfoEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='framespace.Vector.InfoEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='framespace.Vector.InfoEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=653,
  serialized_end=696,
)

_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='framespace.Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='framespace.Vector.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='framespace.Vector.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contents', full_name='framespace.Vector.contents', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='framespace.Vector.info', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_VECTOR_INFOENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=529,
  serialized_end=696,
)


_DATAFRAME_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='framespace.DataFrame.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='framespace.DataFrame.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='framespace.DataFrame.MetadataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=337,
)

_DATAFRAME = _descriptor.Descriptor(
  name='DataFrame',
  full_name='framespace.DataFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='framespace.DataFrame.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='major', full_name='framespace.DataFrame.major', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minor', full_name='framespace.DataFrame.minor', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='framespace.DataFrame.metadata', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contents', full_name='framespace.DataFrame.contents', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATAFRAME_METADATAENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=699,
  serialized_end=940,
)


_KEYCELLMAP = _descriptor.Descriptor(
  name='KeyCellMap',
  full_name='framespace.KeyCellMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='framespace.KeyCellMap.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='framespace.KeyCellMap.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=942,
  serialized_end=1017,
)

_KEYSPACE_METADATAENTRY.containing_type = _KEYSPACE
_KEYSPACE.fields_by_name['axis'].message_type = _AXIS
_KEYSPACE.fields_by_name['keys'].message_type = _KEY
_KEYSPACE.fields_by_name['metadata'].message_type = _KEYSPACE_METADATAENTRY
_DIMENSION.fields_by_name['keys'].message_type = _KEY
_CELL.oneofs_by_name['cell_type'].fields.append(
  _CELL.fields_by_name['float_data'])
_CELL.fields_by_name['float_data'].containing_oneof = _CELL.oneofs_by_name['cell_type']
_CELL.oneofs_by_name['cell_type'].fields.append(
  _CELL.fields_by_name['str_data'])
_CELL.fields_by_name['str_data'].containing_oneof = _CELL.oneofs_by_name['cell_type']
_CELL.oneofs_by_name['cell_type'].fields.append(
  _CELL.fields_by_name['bool_data'])
_CELL.fields_by_name['bool_data'].containing_oneof = _CELL.oneofs_by_name['cell_type']
_CELL.oneofs_by_name['cell_type'].fields.append(
  _CELL.fields_by_name['int_data'])
_CELL.fields_by_name['int_data'].containing_oneof = _CELL.oneofs_by_name['cell_type']
_CELL.oneofs_by_name['cell_type'].fields.append(
  _CELL.fields_by_name['sint_data'])
_CELL.fields_by_name['sint_data'].containing_oneof = _CELL.oneofs_by_name['cell_type']
_VECTOR_INFOENTRY.containing_type = _VECTOR
_VECTOR.fields_by_name['contents'].message_type = _KEYCELLMAP
_VECTOR.fields_by_name['info'].message_type = _VECTOR_INFOENTRY
_DATAFRAME_METADATAENTRY.containing_type = _DATAFRAME
_DATAFRAME.fields_by_name['major'].message_type = _DIMENSION
_DATAFRAME.fields_by_name['minor'].message_type = _DIMENSION
_DATAFRAME.fields_by_name['metadata'].message_type = _DATAFRAME_METADATAENTRY
_DATAFRAME.fields_by_name['contents'].message_type = _VECTOR
_KEYCELLMAP.fields_by_name['key'].message_type = _KEY
_KEYCELLMAP.fields_by_name['value'].message_type = _CELL
DESCRIPTOR.message_types_by_name['Axis'] = _AXIS
DESCRIPTOR.message_types_by_name['Key'] = _KEY
DESCRIPTOR.message_types_by_name['KeySpace'] = _KEYSPACE
DESCRIPTOR.message_types_by_name['Dimension'] = _DIMENSION
DESCRIPTOR.message_types_by_name['Cell'] = _CELL
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
DESCRIPTOR.message_types_by_name['DataFrame'] = _DATAFRAME
DESCRIPTOR.message_types_by_name['KeyCellMap'] = _KEYCELLMAP

Axis = _reflection.GeneratedProtocolMessageType('Axis', (_message.Message,), dict(
  DESCRIPTOR = _AXIS,
  __module__ = 'proto.framespace.framespace_pb2'
  # @@protoc_insertion_point(class_scope:framespace.Axis)
  ))
_sym_db.RegisterMessage(Axis)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), dict(
  DESCRIPTOR = _KEY,
  __module__ = 'proto.framespace.framespace_pb2'
  # @@protoc_insertion_point(class_scope:framespace.Key)
  ))
_sym_db.RegisterMessage(Key)

KeySpace = _reflection.GeneratedProtocolMessageType('KeySpace', (_message.Message,), dict(

  MetadataEntry = _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), dict(
    DESCRIPTOR = _KEYSPACE_METADATAENTRY,
    __module__ = 'proto.framespace.framespace_pb2'
    # @@protoc_insertion_point(class_scope:framespace.KeySpace.MetadataEntry)
    ))
  ,
  DESCRIPTOR = _KEYSPACE,
  __module__ = 'proto.framespace.framespace_pb2'
  # @@protoc_insertion_point(class_scope:framespace.KeySpace)
  ))
_sym_db.RegisterMessage(KeySpace)
_sym_db.RegisterMessage(KeySpace.MetadataEntry)

Dimension = _reflection.GeneratedProtocolMessageType('Dimension', (_message.Message,), dict(
  DESCRIPTOR = _DIMENSION,
  __module__ = 'proto.framespace.framespace_pb2'
  # @@protoc_insertion_point(class_scope:framespace.Dimension)
  ))
_sym_db.RegisterMessage(Dimension)

Cell = _reflection.GeneratedProtocolMessageType('Cell', (_message.Message,), dict(
  DESCRIPTOR = _CELL,
  __module__ = 'proto.framespace.framespace_pb2'
  # @@protoc_insertion_point(class_scope:framespace.Cell)
  ))
_sym_db.RegisterMessage(Cell)

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), dict(

  InfoEntry = _reflection.GeneratedProtocolMessageType('InfoEntry', (_message.Message,), dict(
    DESCRIPTOR = _VECTOR_INFOENTRY,
    __module__ = 'proto.framespace.framespace_pb2'
    # @@protoc_insertion_point(class_scope:framespace.Vector.InfoEntry)
    ))
  ,
  DESCRIPTOR = _VECTOR,
  __module__ = 'proto.framespace.framespace_pb2'
  # @@protoc_insertion_point(class_scope:framespace.Vector)
  ))
_sym_db.RegisterMessage(Vector)
_sym_db.RegisterMessage(Vector.InfoEntry)

DataFrame = _reflection.GeneratedProtocolMessageType('DataFrame', (_message.Message,), dict(

  MetadataEntry = _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), dict(
    DESCRIPTOR = _DATAFRAME_METADATAENTRY,
    __module__ = 'proto.framespace.framespace_pb2'
    # @@protoc_insertion_point(class_scope:framespace.DataFrame.MetadataEntry)
    ))
  ,
  DESCRIPTOR = _DATAFRAME,
  __module__ = 'proto.framespace.framespace_pb2'
  # @@protoc_insertion_point(class_scope:framespace.DataFrame)
  ))
_sym_db.RegisterMessage(DataFrame)
_sym_db.RegisterMessage(DataFrame.MetadataEntry)

KeyCellMap = _reflection.GeneratedProtocolMessageType('KeyCellMap', (_message.Message,), dict(
  DESCRIPTOR = _KEYCELLMAP,
  __module__ = 'proto.framespace.framespace_pb2'
  # @@protoc_insertion_point(class_scope:framespace.KeyCellMap)
  ))
_sym_db.RegisterMessage(KeyCellMap)


_KEYSPACE_METADATAENTRY.has_options = True
_KEYSPACE_METADATAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_VECTOR_INFOENTRY.has_options = True
_VECTOR_INFOENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_DATAFRAME_METADATAENTRY.has_options = True
_DATAFRAME_METADATAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
import abc
from grpc.beta import implementations as beta_implementations
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
